window.jin_list = [
    "Abyss",
    "The Astronaut",
    "Tonight",
    "Super Tuna (OG Version)",
    "Yours",
    "It's Definitely You (Feat. V)",
    "I'll Be There",
    "Super Tuna (Extended)",
    "Another Level",
    "Running Wild",
    "Heart on the Window (with Wendy)",
    "I will come to you",
    "Falling",
    "Close to You",
    "Falling (Feat. Taka)",
    "Epiphany",
    "Moon",
    "Awake",
    "Don't Say You Love Me",
    "Loser",
    "Rope it",
    "A Journey With The Clouds",
    "Background",
    "Nothing Without Your Love",
    "To Today's Me"
];
